"""
Scripts package for HeatmapVLN.

User-facing entrypoints:
    python scripts/run.py ...
Compatibility entrypoints:
    python scripts/train.py ...
    python scripts/evaluate.py ...
    python scripts/visualize.py ...
    python scripts/inference.py ...
"""

__all__ = []