#!/usr/bin/env bash
set -Eeuo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/stage_training_common.sh"

STAGE2_CONFIG="${STAGE2_CONFIG:-configs/train_config_internnav_8gpu.yaml}"
PANORAMIC_DATA_ROOT="${PANORAMIC_DATA_ROOT:-${DATA_ROOT:-/workspace/r2r_panoramic_data}}"
STAGE2_DATA_ROOT="${STAGE2_DATA_ROOT:-$PANORAMIC_DATA_ROOT}"
STAGE1_S2_OUT_DIR="${STAGE1_S2_OUT_DIR:-${SYSTEM2_SFT_OUT_DIR:-/root/autodl-tmp/vln_system2_sft_outputs}}"
STAGE1_S2_CHECKPOINT_PREFERENCE="${STAGE1_S2_CHECKPOINT_PREFERENCE:-latest}"
STAGE2_LOAD_WEIGHTS="${STAGE2_LOAD_WEIGHTS:-${BASE_CHECKPOINT:-}}"
STAGE2_INTERNNAV_MODEL="${STAGE2_INTERNNAV_MODEL:-$INTERNNAV_MODEL_PATH}"
STAGE2_SYSTEM1_CKPT="${STAGE2_SYSTEM1_CKPT:-}"
STAGE2_DAV2_CKPT="${STAGE2_DAV2_CKPT:-}"
STAGE2_REQUIRE_DAV2_CKPT="${STAGE2_REQUIRE_DAV2_CKPT:-0}"
STAGE2_OUT_DIR="${STAGE2_OUT_DIR:-/root/autodl-tmp/vln_training_outputs}"
STAGE2_TB_DIR="${STAGE2_TB_DIR:-/root/tf-logs-stage2}"
STAGE2_EPOCHS="${STAGE2_EPOCHS:-}"
STAGE2_BATCH_SIZE="${STAGE2_BATCH_SIZE:-6}"
STAGE2_GRAD_ACCUM_STEPS="${STAGE2_GRAD_ACCUM_STEPS:-1}"
STAGE2_NUM_WORKERS="${STAGE2_NUM_WORKERS:-8}"
STAGE2_PREFETCH_FACTOR="${STAGE2_PREFETCH_FACTOR:-2}"
STAGE2_PIN_MEMORY="${STAGE2_PIN_MEMORY:-true}"
STAGE2_MAX_BATCHES="${STAGE2_MAX_BATCHES:-}"
STAGE2_CHECKPOINT_PREFERENCE="${STAGE2_CHECKPOINT_PREFERENCE:-latest}"
STAGE2_FEISHU_NOTIFY="${STAGE2_FEISHU_NOTIFY:-$FEISHU_NOTIFY}"
MASTER_PORT_STAGE2="${MASTER_PORT_STAGE2:-29618}"

if [[ -z "$STAGE2_LOAD_WEIGHTS" ]]; then
  STAGE2_LOAD_WEIGHTS="$(choose_checkpoint "${STAGE1_S2_OUT_DIR}/latest/checkpoints" "$STAGE1_S2_CHECKPOINT_PREFERENCE")"
fi

preflight_gpu
preflight_notify "$STAGE2_FEISHU_NOTIFY"
require_file "$STAGE2_CONFIG"
require_file "$STAGE2_LOAD_WEIGHTS"
require_hf_model_dir "$INTERNNAV_BACKBONE"
require_dir "$STAGE2_DATA_ROOT"
require_file "$ROOT_DIR/data/fgr2r/subinstr_mapping.json.gz"
prepare_stage2_assets
mkdir -p "$STAGE2_OUT_DIR" "$STAGE2_TB_DIR"

STAGE2_TMP_CONFIG="$(mktemp "/tmp/stage2.XXXXXX")"
TMP_CONFIGS+=("$STAGE2_TMP_CONFIG")

export GPU_DEVICES
export STAGE2_DATA_ROOT STAGE2_OUT_DIR STAGE2_TB_DIR
export STAGE2_EPOCHS STAGE2_BATCH_SIZE STAGE2_GRAD_ACCUM_STEPS
export STAGE2_NUM_WORKERS STAGE2_PREFETCH_FACTOR STAGE2_PIN_MEMORY
export STAGE2_FEISHU_NOTIFY STAGE2_INTERNNAV_MODEL STAGE2_SYSTEM1_CKPT

make_stage_config STAGE2 "$STAGE2_CONFIG" "$STAGE2_TMP_CONFIG"

log "Stage: Stage2 bridge-only"
log "Repo root: $ROOT_DIR"
log "Training GPUs: $GPU_DEVICES (nproc_per_node=$NPROC_PER_NODE)"
log "InternNav backbone: $INTERNNAV_BACKBONE"
log "Config: $STAGE2_TMP_CONFIG"
log "Load weights: $STAGE2_LOAD_WEIGHTS"
log "Output dir: $STAGE2_OUT_DIR"

if is_truthy "$STAGE_DRY_RUN"; then
  log "STAGE_DRY_RUN=$STAGE_DRY_RUN; preflight and config generation completed, skipping training"
  exit 0
fi

run_training_stage "Stage2 bridge-only" "$MASTER_PORT_STAGE2" \
  "$STAGE2_TMP_CONFIG" "$STAGE2_LOAD_WEIGHTS" "$STAGE2_MAX_BATCHES"

FINAL_CKPT="$(choose_checkpoint "${STAGE2_OUT_DIR}/latest/checkpoints" "$STAGE2_CHECKPOINT_PREFERENCE")"
log "Stage2 checkpoint: $FINAL_CKPT"
